build: make --load and --push exclusive.
Docker buildx doesn't support --load and --push specified at the same
time. Or, it fails with:

  ERROR: failed to build: failed to solve: image "...:X.Y": already exists