Dockerfile: fix missing libdw1t64 and libelf1t64
$ apt install --no-install-recommends --yes aptitude
;You might want to run 'apt --fix-broken install' to correct these.
Unsatisfied dependencies:
 aptitude : Depends: aptitude-common (= 0.8.13-7ubuntu5) but it is not going to be installed
            Depends: libboost-iostreams1.90.0 (>= 1.90.0) but it is not going to be installed
            Depends: libcwidget4 (>= 0.5.18-1) but it is not going to be installed
            Depends: libsigc++-2.0-0v5 (>= 2.8.0) but it is not going to be installed
            Depends: libsqlite3-0 (>= 3.6.5) but it is not going to be installed
            Depends: libxapian30 (>= 1.4.28~) but it is not going to be installed
 linux-headers-7.0.0-070000-generic : Depends: libdw1t64 (>= 0.171) but it is not going to be installed
                                      Depends: libelf1t64 (>= 0.144) but it is not going to be installed
 linux-headers-7.0.1-070001-generic : Depends: libdw1t64 (>= 0.171) but it is not going to be installed
                                      Depends: libelf1t64 (>= 0.144) but it is not going to be installed
 linux-headers-7.0.2-070002-generic : Depends: libdw1t64 (>= 0.171) but it is not going to be installed
                                      Depends: libelf1t64 (>= 0.144) but it is not going to be installed
 linux-headers-7.0.3-070003-generic : Depends: libdw1t64 (>= 0.171) but it is not going to be installed
                                      Depends: libelf1t64 (>= 0.144) but it is not going to be installed
Error: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).